### ISSUE TITLE
Minor issue in config.py related to AllenCahn equation

### ISSUE THREAD

**Issue by parsiad** [frankhan91/DeepBSDE#1]
I read your DeepBSDE paper on arXiv and am now playing around with your DeepBSDE solver. Great work, and a great idea.

Trying to run the AllenCahn solver out of the box, I noticed that `lr_values` and `lr_boundaries` don't match, so you get an error of the form

> ValueError: The length of boundaries should be 1 less than the length of values

Just thought I'd post that here in case future users encounter the same problem.

Thanks!

**Comment by frankhan91** [comment]
Thanks for your interests in our work and pointing out the bug! Just fixed it :-)
