### ISSUE TITLE
Question about boundary condition

### ISSUE THREAD

**Issue by w140601** [frankhan91/DeepBSDE#2]
Hi, I was going through your paper on Arxiv and trying out the solver. It's a great work.
I was wondering how do you deal with boundary conditions in PDE as there's only initial(terminal) condition s specified in the solver.
Thanks a lot.

**Comment by frankhan91** [comment]
Thanks for your interests in our work. The current paper and codes only consider the situation where the domain is R^d, without any boundary. So there are no space boundary conditions specified in the solver. There are BSDEs corresponding to PDEs with space boundary conditions and our idea should also be applicable. But it is beyond the scope of the current paper and solver. 

I am open to discussion if you can provide more details of your problems.

**Comment by w140601** [comment]
Thanks for the reply.  I'm in the field of Materials Science and we were using the conventional method to solve Allen Cahn equation on R^3 domain with periodic space boundary mostly.  I was wondering as the periodic boundary is just a way to represent the infinite space, do I need to make modifications to your solver?
