### ISSUE TITLE
Issue with Equation.sample method when in 1 dimension

### ISSUE THREAD

**Issue by BrownianNotion** [frankhan91/DeepBSDE#4]
Hi Frank, awesome paper and very clean code, thank you for sharing it publicly!

There seems to be an issue with the sample method of the Equation class when considering 1-dimensional equations (eg. line 39 of Equation.py). Unfortunately, scipy's multivariate normal seems to remove the second dimension when self.dim=1, resulting in an indexing error when doing x_sample[:, :, 0] as x_sample will be of shape (num_sample, self.num_time_interval). I am running scipy 1.6.2.

**Comment by frankhan91** [comment]
Yes, you are right. Thank you for reporting this issue. I will fix this problem when I finish travel two weeks later.
