### ISSUE TITLE
Question about the solver.py

### ISSUE THREAD

**Issue by Field97** [frankhan91/DeepBSDE#5]
Hi, Mr. Han! In the file, solver.py, I wonder why subnets are denoted by **z = self.subnet[t](x[:, :, t + 1], training) / self.bsde.dim**
rather than **z = self.subnet[t](x[:, :, t + 1], training)** (the code is in the NonsharedModel class).

**Comment by frankhan91** [comment]
Both options are fine in general. They are mathematically equivalent and give similar results in low dimensions. Here I scaled the z component by a factor 1/d mainly to avoid too large output from the term z * dw in the initial period of training when d is large (~100).

**Comment by Field97** [comment]
Very clear answer! Thanks for the reply.
