### ISSUE TITLE
monte carlo comparison

### ISSUE THREAD

**Issue by rushhan** [frankhan91/DeepBSDE#6]
Hi,
Thank you very much for the library.
I am comparing the results with different lambda with the ones in the paper, but they don't seem to match. For example with lambda = 40, I get Y0 of 6.2449e-01, which is different from that in the paper. I am simply changing lambda here to 40 with everything else the same .  [line 35- equation.py]. Is this the correct approach?
        self.lambd = 40.0
Also is it possible to get the corresponding code for monte carlo simulation for HJBLQ?

Thanks in advance.

**Comment by frankhan91** [comment]
Changing lambda in equation.py (line 35) is the correct approach. However, as lambda increases, the problem becomes more and more challenging to solve, which requires changing some parameters and much much longer computation time. So it is not quite recommended to compute large lambda for a benchmark test. If needed, for lambda = 10, you may change yinit to around 4, increase the batch size to 1024 and use 20000 or 40000 epochs.

The Monte Carlo simulation to HJBLQ should be quite straightforward. It is purely based on Eqn 14 in our PNAS paper. Let me know if you need further help.
